MagniSchool/Controllers/AlunoController.cs
using MagniSchool.Models;
using MagniSchool.Repository.Interface;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MagniSchool.Controllers
{
    public class AlunoController : Controller
    {

        private readonly IAlunoRepository _alunoRepository;
        public AlunoController(IAlunoRepository alunoRepository)
        {
            _alunoRepository = alunoRepository;
        }

        // GET: AlunoController
        public ActionResult Index()
        {
            return View();
        }

        // GET: AlunoController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AlunoController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AlunoController/Create
        [HttpPost]
        public ActionResult Create(Aluno aluno)
        {
           
                if (ModelState.IsValid)
                {
                    _alunoRepository.Adicionar(aluno);
                    return RedirectToAction("Index");
                }
                return View(aluno);
           

        }

        // GET: AlunoController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AlunoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AlunoController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AlunoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MagniSchool/Controllers/CursoController.cs
using MagniSchool.Models;

using MagniSchool.Repository.Interface;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace MagniSchool.Controllers
{
    public class CursoController : Controller
    {
        private readonly ICursoRepository _cursoRepository;
        public CursoController(ICursoRepository cursoRepository)
        {
            _cursoRepository= cursoRepository;
        }
        public IActionResult Index()
        {
            List<Curso> cursos= _cursoRepository.BuscarTodos();
            return View(cursos);
        }
        public IActionResult Edit(int id)
        {
            Curso curso = _cursoRepository.BuscarCursoPorId(id);
            return View(curso);

        }

        public IActionResult Delete(int id)
        {
            Curso curso = _cursoRepository.BuscarCursoPorId(id);
            return View(curso);
        }

        public IActionResult DeleteAll(int id)
        {
            _cursoRepository.Deletar(id);
            return RedirectToAction("Index");
        }

        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public IActionResult Create( Curso curso)
        {
            if(ModelState.IsValid)
            {
                _cursoRepository.Adicionar(curso);
                return RedirectToAction("Index");
            }

            return View(curso);


        }

        [HttpPost]
        public IActionResult Alterar(Curso curso)
        {
            if (ModelState.IsValid)
            {
                _cursoRepository.Atualizar(curso);

                return RedirectToAction("Index");

            }

            return View("Edit",curso);
        }
    }
}

MagniSchool/Controllers/DisciplinaController.cs
using MagniSchool.Models;
using MagniSchool.Repository;
using MagniSchool.Repository.Interface;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace MagniSchool.Controllers
{
    public class DisciplinaController : Controller
    {
        private readonly IDisciplinaRepository _disciplinaRepository;
        public DisciplinaController(IDisciplinaRepository disciplinaRepository)
        {
            _disciplinaRepository= disciplinaRepository;
        }
        public IActionResult Index()
        {
            List<Disciplina> disciplinas = _disciplinaRepository.BuscarTodos();

            return View(disciplinas);
        }

        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Edit(int id)
        {
            Disciplina disciplina = _disciplinaRepository.BuscarPorId(id);

            return View(disciplina);
        }
        public IActionResult Delete(int id)
        {
            Disciplina disciplina = _disciplinaRepository.BuscarPorId(id);

            return View(disciplina);
        }

        [HttpPost]
        public IActionResult Create(Disciplina disciplina)
        {
            if (ModelState.IsValid)
            {
                _disciplinaRepository.Adicionar(disciplina);
                return RedirectToAction("Index");
            } return View(disciplina);
        }

        public IActionResult Alterar(Disciplina disciplina)
        {
            _disciplinaRepository.AtualizarDados(disciplina);
            

            return RedirectToAction("Index");

        }

        public IActionResult Deletar(int id)
        {
           _disciplinaRepository.Deletar(id);


            return RedirectToAction("Index");

        }
    }
}

MagniSchool/Controllers/ProfessorController.cs
using MagniSchool.Models;
using MagniSchool.Repository.Interface;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace MagniSchool.Controllers
{
    public class ProfessorController : Controller
    {
        private readonly IProfessorRepository _professorRepository;
        public ProfessorController(IProfessorRepository professorRepository)
        {
            _professorRepository= professorRepository;
        }
        public IActionResult Index()
        {
            List<Professor> professores = _professorRepository.BuscarTodos();
            return View(professores);
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Delete(int id)
        {
            Professor professor = _professorRepository.BuscarProfessorPorId(id);
            return View(professor);
        }

        

        public IActionResult Edit(int id)
        {
            Professor professor = _professorRepository.BuscarProfessorPorId(id);
            return View(professor);
        }


        [HttpPost]
        public IActionResult Create(Professor professor)
        {

            if(ModelState.IsValid)
            {
                _professorRepository.Adicionar(professor);
                return RedirectToAction("Index");

            }
            return View(professor);
        }

        [HttpPost]
        public IActionResult Edit(Professor professor)
        {
            if (ModelState.IsValid)
            {
                _professorRepository.Atualizar(professor); 
                return RedirectToAction("Index");
            }
            return View(professor);
        }

        public IActionResult Deletar(int id)
        {
            _professorRepository.Deletar(id);

            return RedirectToAction("Index");
        }
    }
}

MagniSchool/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MagniSchool</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MagniSchool</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Curso" asp-action="Index">Cursos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Disciplina" asp-action="Index">Disciplina</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Professor" asp-action="Index">Professores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Nota" asp-action="Index">Notas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aluno" asp-action="Index">Aluno</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MagniSchool - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>